import { ArrowLeft,ArrowRight,Building2,HeartHandshake,Sparkles,Users } from 'lucide-react'
import '../../src/styles.css'

export default async function JoinPage({ searchParams }) {
  const params = (await searchParams) || {}
  const eventId = typeof params.event === 'string' ? params.event : ''
  const volunteerHref = eventId ? `/volunteer-access?event=${encodeURIComponent(eventId)}` : '/volunteer-access'
  return <main className="join-shell"><header className="signup-nav"><a className="brand" href="/"><span className="brand-mark"><HeartHandshake size={21}/></span><span><b>Niyyah</b><small>Purpose meets people</small></span></a><a className="back-home" href="/"><ArrowLeft size={16}/> Back home</a></header><section className="join-intro"><span className="signup-kicker"><Sparkles size={14}/> Login or sign up</span><h1>First, choose your journey.</h1><p>We’ll take you to the right account page, then directly to your volunteer profile or organization workspace.</p>{eventId&&<p className="join-footnote">We’ll take you back to the opportunity you picked once you’re signed in.</p>}</section><div className="join-paths"><article><span className="join-path-icon"><Users/></span><small>For individuals</small><h2>Continue as a volunteer</h2><p>Discover matched opportunities, join events, connect with friends and build a verified record of impact.</p><ul><li>Volunteer profile and interests</li><li>Personalized opportunities</li><li>Hours, levels and badges</li></ul><div className="join-actions"><a className="primary" href={volunteerHref}>Choose volunteer <ArrowRight size={16}/></a></div></article><article className="organization-path"><span className="join-path-icon"><Building2/></span><small>For nonprofits and community groups</small><h2>Continue as an organizer</h2><p>Publish events, manage volunteer requests, review coverage and approve verified hours.</p><ul><li>Organization profile</li><li>Events and applicants</li><li>Coverage and volunteer ranking</li></ul><div className="join-actions"><a className="primary" href="/organizer-access">Choose organizer <ArrowRight size={16}/></a></div></article></div><p className="join-footnote">After authentication, you’ll land directly in the workspace you selected.</p></main>
}
