'use client'

import { useEffect, useState } from 'react'
import { ArrowLeft, Award, Bell, Check, Clock3, Compass, Copy, HeartHandshake, Link2, LoaderCircle, Search, Share2, Sparkles, UserPlus, Users } from 'lucide-react'

const interestOptions=['Faith & learning','Community meals','Volunteering','Creative projects','Sports & wellbeing','Careers & ideas']

export default function ProfileClient({user}){
  const [tab,setTab]=useState('profile'),[data,setData]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const [query,setQuery]=useState(''),[friends,setFriends]=useState({people:[],feed:[],requests:[]})
  const [activity,setActivity]=useState({organizationId:'',eventId:'',role:'',hours:'',date:new Date().toISOString().slice(0,10)})
  const [joinOrgId,setJoinOrgId]=useState(''),[joinTag,setJoinTag]=useState('external')

  const load=async()=>{const r=await fetch('/api/profile');setData(await r.json())}
  const loadFriends=async(q='')=>{const r=await fetch(`/api/friends?q=${encodeURIComponent(q)}`);setFriends(await r.json())}
  useEffect(()=>{load();loadFriends()},[])

  if(!data)return <main className="member-loading"><LoaderCircle className="spin"/><span>Opening your Niyyah profile…</span></main>
  const profile=data.profile
  const update=(key,value)=>setData(d=>({...d,profile:{...d.profile,[key]:value}}))
  const save=async()=>{setBusy(true);setNotice('');const r=await fetch('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});setBusy(false);setNotice(r.ok?'Profile saved.':'We could not save your profile.')}
  const toggleInterest=(item)=>update('interests',profile.interests.includes(item)?profile.interests.filter(v=>v!==item):[...profile.interests,item])
  const addActivity=async(e)=>{e.preventDefault();setBusy(true);const r=await fetch('/api/volunteering',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...activity,hours:Number(activity.hours)})});setBusy(false);if(r.ok){setActivity({organizationId:'',eventId:'',role:'',hours:'',date:new Date().toISOString().slice(0,10)});await load();setNotice('Hours sent to the organization for approval.')}else setNotice('Please complete all activity fields.')}
  const requestMembership=async(e)=>{e.preventDefault();if(!joinOrgId)return;setBusy(true);const r=await fetch('/api/organization-membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organizationId:joinOrgId,tag:joinTag})});setBusy(false);if(r.ok){setJoinOrgId('');await load();setNotice('Request sent. The organization will review it shortly.')}else setNotice('We could not send that request.')}
  const connect=async(friendId)=>{await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({friendId})});setNotice('Connection request sent.')}
  const accept=async(connectionId)=>{await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'accept',connectionId})});await loadFriends(query)}
  const shareBadge=async(badge)=>{const text=`I unlocked the ${badge.badge} badge on Niyyah after ${data.progress.hours} volunteering hours!`;if(navigator.share)await navigator.share({title:'My Niyyah progress',text,url:location.origin});else{await navigator.clipboard.writeText(`${text} ${location.origin}`);setNotice('Badge message copied—paste it into your social post.')}}
  const copyInvite=async()=>{const link=`${location.origin}/signup?ref=${data.challenge.inviteCode}`;await navigator.clipboard.writeText(link);setNotice('Your Pass the Niyyah invite link is copied. Send it to three friends!')}

  return <main className="member-shell">
    <header className="member-nav"><a className="brand" href="/"><span className="brand-mark"><HeartHandshake size={21}/></span><span><b>Niyyah</b><small>Purpose meets people</small></span></a><a href="/opportunities" className="back-home"><Compass size={16}/> Discover</a><a href="/api/auth/signout?return_to=/" className="signout-link">Sign out</a></header>
    <section className="member-hero"><div className="profile-avatar">{(profile.display_name||user.displayName).slice(0,1).toUpperCase()}</div><div><span className="signup-kicker">Your community profile</span><h1>{profile.display_name||user.displayName}</h1><p>{profile.bio||'Add a short bio so your Niyyah connections can get to know you.'}</p></div><div className="level-chip"><Award size={19}/><span>Level {data.progress.level}<b>{data.progress.name}</b></span></div></section>
    <nav className="member-tabs" aria-label="Volunteer dashboard sections">{[['profile','My profile'],['friends','Friends’ activity'],['progress','My volunteering']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{id==='friends'?<Users size={16}/>:id==='progress'?<Award size={16}/>:<Sparkles size={16}/>} {label}</button>)}<a className="member-tab-link" href="/opportunities"><Compass size={16}/> Discover opportunities</a></nav>
    {notice&&<div className="member-notice" role="status">{notice}</div>}
    {data.challenge.notifications.length>0&&<section className={`challenge-notification ${data.challenge.complete?'complete':''}`}><Bell size={19}/><div><b>{data.challenge.complete?'Challenge complete — you passed the Niyyah!':data.challenge.notifications[0].message}</b><span>{data.challenge.complete?'Three friends created volunteer accounts through your link.':`${data.challenge.completedCount} of 3 friends have joined.`}</span></div></section>}

    {tab==='profile'&&<div className="member-grid profile-grid"><section className={`member-card wide pass-niyyah-card ${data.challenge.complete?'complete':''}`}><div><span className="signup-kicker"><Link2 size={14}/> Pass the Niyyah challenge</span><h2>{data.challenge.complete?'You completed the chain!':'Invite three friends to Niyyah'}</h2><p>Your challenge finishes when three friends use your link and create volunteer accounts.</p><div className="challenge-people">{[0,1,2].map(index=><span className={index<data.challenge.completedCount?'joined':''} key={index}>{index<data.challenge.completedCount?<Check/>:<UserPlus/>}<b>{index<data.challenge.completedCount?'Joined':'Invite'}</b></span>)}</div></div><div className="challenge-action"><strong>{Math.min(3,data.challenge.completedCount)}/3</strong><button onClick={copyInvite}><Copy size={15}/>{data.challenge.complete?'Copy link again':'Copy invite link'}</button></div></section><section className="member-card wide"><div className="card-title"><span>01</span><div><h2>Profile details</h2><p>Update what other Niyyah members can see.</p></div></div><div className="field-grid two"><label>Display name<input value={profile.display_name||''} onChange={e=>update('display_name',e.target.value)}/></label><label>Postcode<input value={profile.postcode||''} onChange={e=>update('postcode',e.target.value)} placeholder="e.g. E1 6AN"/></label></div><label>About me<textarea value={profile.bio||''} onChange={e=>update('bio',e.target.value)} maxLength={280} placeholder="What should your community know about you?"/></label></section>
      <section className="member-card"><div className="card-title"><span>02</span><div><h2>Interests</h2><p>Shape your recommendations.</p></div></div><div className="profile-interests">{interestOptions.map(item=><button key={item} className={profile.interests.includes(item)?'chosen':''} onClick={()=>toggleInterest(item)}>{profile.interests.includes(item)&&<Check size={14}/>} {item}</button>)}</div></section>
      <section className="member-card"><div className="card-title"><span>03</span><div><h2>Social media</h2><p>Every handle is optional.</p></div></div><label>Instagram<input value={profile.instagram||''} onChange={e=>update('instagram',e.target.value)} placeholder="@username"/></label><label>TikTok<input value={profile.tiktok||''} onChange={e=>update('tiktok',e.target.value)} placeholder="@username"/></label><label>Other profile<input value={profile.other_social||''} onChange={e=>update('other_social',e.target.value)} placeholder="Platform and username"/></label></section>
      <section className="member-card wide privacy-card"><div className="card-title"><span>04</span><div><h2>Discovery & privacy</h2><p>You control what your connections can discover.</p></div></div><label className="toggle-row"><input type="checkbox" checked={!!profile.discoverable} onChange={e=>update('discoverable',e.target.checked)}/><span><b>Let people find me</b>Match my display name or optional handles in Niyyah search.</span></label><label className="toggle-row"><input type="checkbox" checked={!!profile.share_activity} onChange={e=>update('share_activity',e.target.checked)}/><span><b>Share my volunteering activity</b>Accepted Niyyah connections can see my recent progress.</span></label></section>
      <section className="member-card wide"><div className="card-title"><span>05</span><div><h2>Organizations</h2><p>Join an organization's roster to volunteer with them. Students with a matching school email are approved automatically — everyone else is reviewed by the organization.</p></div></div>{data.memberships.length>0&&<div className="membership-list">{data.memberships.map(m=><article key={m.organization_id}><div><b>{m.organization_name}</b><span>{m.tag}</span></div><span className={`event-status ${m.status}`}>{m.status}</span></article>)}</div>}<form className="org-form" onSubmit={requestMembership}><div className="field-grid two"><label>Organization<select value={joinOrgId} onChange={e=>setJoinOrgId(e.target.value)}><option value="">Choose an organization</option>{data.organizations.filter(o=>!data.memberships.some(m=>m.organization_id===o.id)).map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>I am a<select value={joinTag} onChange={e=>setJoinTag(e.target.value)}><option value="parent">Parent</option><option value="external">External volunteer</option></select></label></div><button className="profile-save" disabled={busy||!joinOrgId}>{busy?<LoaderCircle className="spin" size={16}/>:<Check size={16}/>} Request to join</button></form></section>
      <button className="profile-save wide" onClick={save} disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} Save profile</button></div>}

    {tab==='friends'&&<div className="member-grid friends-grid"><section className="member-card wide"><div className="card-title"><span><Search size={15}/></span><div><h2>Find your people</h2><p>Search opt-in Niyyah members by name or optional social handle.</p></div></div><form className="friend-search" onSubmit={e=>{e.preventDefault();loadFriends(query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, Instagram or TikTok handle"/><button><Search size={16}/> Search</button></form><div className="people-results">{friends.people.length?friends.people.map(person=><article key={person.user_id}><div className="mini-avatar">{person.display_name.slice(0,1)}</div><div><b>{person.display_name}</b><span>{person.instagram||person.tiktok||person.interests.slice(0,2).join(' · ')}</span></div><button onClick={()=>connect(person.user_id)}><UserPlus size={15}/> Connect</button></article>):<p className="empty-copy">Search for friends who have chosen to be discoverable.</p>}</div></section>
      {friends.requests.length>0&&<section className="member-card wide"><div className="card-title"><span><UserPlus size={15}/></span><div><h2>Connection requests</h2></div></div>{friends.requests.map(request=><div className="request-row" key={request.id}><b>{request.display_name}</b><button onClick={()=>accept(request.id)}>Accept</button></div>)}</section>}
      <section className="member-card wide"><div className="card-title"><span><Users size={15}/></span><div><h2>Friends’ community activity</h2><p>Only activity your accepted connections choose to share.</p></div></div><div className="activity-feed">{friends.feed.length?friends.feed.map((item,index)=><article key={`${item.display_name}-${index}`}><div className="feed-dot"/><div><b>{item.display_name}</b><p>Volunteered as {item.role} with {item.organization}</p><span><Clock3 size={13}/> {item.hours} hours · {item.activity_date}</span></div></article>):<p className="empty-copy">Connect with friends to see their shared volunteering progress here.</p>}</div></section></div>}

    {tab==='progress'&&<div className="member-grid progress-grid"><section className="member-card progress-card wide"><div className="progress-top"><div><span className="signup-kicker">Your current level</span><h2>Level {data.progress.level}: {data.progress.name}</h2><p>{data.progress.hours} approved volunteering hours across organizations</p></div><span className="big-badge"><Award size={34}/>{data.progress.badge}</span></div><div className="progress-track"><span style={{width:`${data.progress.percent}%`}}/></div><small>{data.progress.next?`${data.progress.next-data.progress.hours} hours to your next level`:'Top level reached—keep making an impact!'}</small></section>
      <section className="member-card"><div className="card-title"><span>+</span><div><h2>Log volunteering</h2><p>Your organization will approve these hours.</p></div></div><form className="activity-form" onSubmit={addActivity}><label>Organization<select value={activity.organizationId} onChange={e=>setActivity({...activity,organizationId:e.target.value,eventId:''})} required><option value="">Choose an organization</option>{data.organizations.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Event <small>Optional</small><select value={activity.eventId} onChange={e=>setActivity({...activity,eventId:e.target.value})}><option value="">General volunteering</option>{data.events.filter(item=>item.organization_id===activity.organizationId).map(item=><option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label>Your role<input value={activity.role} onChange={e=>setActivity({...activity,role:e.target.value})} required/></label><div className="field-grid two"><label>Hours<input type="number" min="1" max="1000" value={activity.hours} onChange={e=>setActivity({...activity,hours:e.target.value})} required/></label><label>Date<input type="date" value={activity.date} onChange={e=>setActivity({...activity,date:e.target.value})} required/></label></div><button className="profile-save" disabled={busy}>Send for approval</button></form></section>
      <section className="member-card"><div className="card-title"><span><Award size={15}/></span><div><h2>Your badges</h2><p>Share each milestone with your community.</p></div></div><div className="badge-grid">{data.progress.unlocked.map(badge=><article key={badge.level}><span><Award size={24}/></span><div><b>{badge.badge}</b><small>Level {badge.level}</small></div><button onClick={()=>shareBadge(badge)} aria-label={`Share ${badge.badge} badge`}><Share2 size={15}/></button></article>)}</div></section>
      <section className="member-card wide"><div className="card-title"><span><Clock3 size={15}/></span><div><h2>Your volunteering timeline</h2><p>Approved activities count toward your level and badges.</p></div></div><div className="timeline">{data.activities.length?data.activities.map(item=><article key={item.id}><span>{item.hours}h</span><div><b>{item.role}</b><p>{item.organization} · {item.activity_date}</p></div><small>{item.status.replace('_',' ')}</small></article>):<p className="empty-copy">Your first volunteering activity will appear here.</p>}</div></section></div>}
  </main>
}
